# -*- coding: utf-8 -*-
"""fetch_cfpb_data.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rXvAimgwoxoJlcqsde22rJfDR9bJFyxQ
"""

!pip install anthropic

import requests
import pandas as pd
import json
import os
import sys

# Ensure the library is available for the fallback function
try:
    import anthropic
except ImportError:
    print("📦 Installing missing dependency: anthropic...")
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "anthropic"])
    import anthropic

CFPB_API = "https://www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/"

def fetch_complaints(product: str = "Credit card", size: int = 100) -> pd.DataFrame:
    """
    Fetches real complaints from CFPB API with headers to avoid 403 errors.
    """
    # Adding a User-Agent header is the key to bypassing most 403 Forbidden errors
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
        "Accept": "application/json"
    }

    params = {
        "product": product,
        "has_narrative": "true",
        "size": size,
        "sort": "created_date_desc",
        "field": "all"
    }

    print(f"🌐 Fetching {size} complaints for '{product}' from CFPB...")
    response = requests.get(CFPB_API, params=params, headers=headers)
    response.raise_for_status()

    data = response.json()
    hits = data.get("hits", {}).get("hits", [])

    records = []
    for hit in hits:
        src = hit.get("_source", {})
        records.append({
            "complaint_id": src.get("complaint_id", ""),
            "narrative": src.get("complaint_what_happened", ""),
            "product": src.get("product", ""),
            "sub_product": src.get("sub_product", ""),
            "issue": src.get("issue", ""),
            "sub_issue": src.get("sub_issue", ""),
            "company": src.get("company", ""),
            "state": src.get("state", ""),
            "date_received": src.get("date_received", ""),
            "company_response": src.get("company_response", ""),
            "timely_response": src.get("timely_response", ""),
        })

    df = pd.DataFrame(records)

    # Filter for quality narratives
    if not df.empty:
        df = df[df["narrative"].str.len() > 50].copy()

    os.makedirs("data", exist_ok=True)
    df.to_csv("data/complaints.csv", index=False)
    print(f"✅ Successfully fetched {len(df)} complaints.")
    return df


def generate_synthetic_data(n: int = 50) -> pd.DataFrame:
    """
    Generates synthetic data using Anthropic API.
    Requires ANTHROPIC_API_KEY environment variable.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise ValueError("Missing ANTHROPIC_API_KEY environment variable.")

    client = anthropic.Anthropic(api_key=api_key)

    prompt = f"""Generate {n} realistic fintech customer complaint narratives as a JSON array.
Each object must have:
- narrative: detailed complaint text (100-300 words)
- product: one of ["Credit card", "Personal loan", "Checking account", "Digital banking"]
- severity: one of ["low", "medium", "high", "critical"]
- true_issue: brief description of the core problem

Return ONLY a valid JSON array. No markdown, no preamble."""

    message = client.messages.create(
        model="claude-3-sonnet-20240229", # Updated to a standard stable model name
        max_tokens=4000,
        messages=[{"role": "user", "content": prompt}]
    )

    raw = message.content[0].text.strip()
    data = json.loads(raw)
    df = pd.DataFrame(data)

    os.makedirs("data", exist_ok=True)
    df.to_csv("data/synthetic_complaints.csv", index=False)
    print(f"✅ Generated {len(df)} synthetic complaints.")
    return df


if __name__ == "__main__":
    try:
        # Step 1: Try real data
        df = fetch_complaints(product="Credit card", size=100)
    except Exception as e:
        print(f"❌ CFPB fetch failed: {e}")

        # Step 2: Fallback to synthetic data
        print("🤖 Attempting to generate synthetic data...")
        try:
            df = generate_synthetic_data(10)
        except Exception as synth_e:
            print(f"❌ Synthetic generation failed: {synth_e}")
            df = pd.DataFrame() # Return empty DF if both fail

    if not df.empty:
        print("\n--- Data Preview ---")
        print(df.head())
    else:
        print("No data collected.")
